---
# install Apache2 using Ansible
- name: Setup Apache server on myservers
  hosts: webserver
  become: True
  vars:
    apache2_version: 2.4.41
  tasks:

    # Initial task --- instal necessary tools
    - name: Install apt and upgrade       
      command: sudo apt-get -y install net-tools 

    # first task --- instal apache2
    - name: Install the latest version of apache2
      command: sudo apt install apache2 apache2-utils -y

    
    #second task --- start the service
    - name: Start apache2
      service:
        name: apache2
        enabled: yes
        state: started

    # third task --- confirm apache2 version
    - name: Get apache2 installed version
      command: apache2 -v
      register: apache2_version
    
    # forth task --- start status
    - name: Start apache2 service
      command: systemctl start apache2
   
    # fifth task --- enable apache2
    - name: Enable apache2 
      command: systemctl enable apache2

    # sixth task --- confirm status
    - name: Get the status of apache2 service
      command: systemctl status apache2

    # forth task --- start status
    - name: Start apache2 service
      command: systemctl restart apache2

    # seventh task --- set server to Africa/Lagos timezone
    - name: Set timezone to Africa/Lagos
      command: timedatectl set-timezone Africa/Lagos

    # eight task --- confirm time zone has been changed correctly
    - name: Get status of timezone
      command: timedatectl

    #Install php8.1
    - name: install php software packages
      command: apt install lsb-release ca-certificates apt-transport-https software-properties-common -y

    - name: Add repository ppa:ondrej/php
      apt_repository:
        repo: "ppa:ondrej/php"

    - name: Updating the repo
      apt: update_cache=yes

    - name: installing php8.0
      apt: name=php8.0 state=latest

   
    #Copy index.html file to various server path
   # - name: copy files to respective servers
    #  copy:
     #   src: /home/vagrant/terraform/ansible/index.html
      #  dest: /var/www/html/index.html


    #- hosts: server1
     # become: true
      #tasks:
    #- name: copy html file to server 1
    #  copy: src=/home/vagrant/terraform/ansible/index.html> dest=/var/www/html/index.html  mode=0744


    - name: servers
      tags: printf
      shell: echo "<h1>Nielas $(ansiblehost -f)</h1>" > /var/www/html/index.html
